language: php

php:
- '7.3'

before_script:
- cp .env.travis .env
- mysql -e 'create database statify_test;'
- composer self-update
- composer install --no-interaction
- php artisan key:generate

addons:
  sonarcloud:
    organization: jacksonmcdaniel-github
    token:
      secure: VVcG5UnCUHX1GI03y5wM6zp6Pd+Z/ybWoGIYXr4eX93VfQs3/mvk9FqYrv5wTGIbh9MWcBQGoe8WG+RWlFmTeZA/Yc+T2khDZm/2CK7occQtb/BK6K8WKzfKo8qI8SKQ1t2Xl9bSyIeU/JzDASbXmNK1q88ceCZiY7sJfouRzPRy+z0VkGXLQFDHUoUEWnPD+nenl5WHmUHZ9uTRe95InczJjbvvDjIQaIT+TgybSWxELcqID8uyLaSRxrbvNBmyAO4vltiuKsZAB63mTdaLaeuj20+Yy68ppgRrwDTn6PnX/4Y2Qx4TdoJ+5Bt41FfYX5lEmt9b/L0gKw3UKuVWJPrG3P0AfuHJcE6Va8T4rqBs/y6gzX7RL3TqQwL0zHdjMHxuq+8pIvHeGKObHxFZLTuDoW+DYzHeChSiTDMmUz1lDY8Uk+ZdohFw7BT38wNggEmlM9w+bGB9NWrnfiIhCsu0S6SoAPJPW1pXEH4RBZBXWRTzq7fF0tvzx72OqY2S5NxoQVWWyJYn++C3jGi0QZjDJ2lcoBAt4+Odkezb0H7DFo5WMWSiL2rPcdQtgOnv12Lt7sATZgaZbISeKMv++VvQIPzMjKWm4zgVdZfb50lRKyHl8K7oD+JXra6ySyQSk6c8jjL1an71ckSv/hZd/GrgxWtop4Vw+4Jo8ElPvwM=

script:
- vendor/bin/phpunit
- sonar-scanner

notifications:
  email: false
